### ISSUE TITLE
version is lower but cannot update

### ISSUE THREAD

**Issue by timecool-cpu** [ipfs/fs-repo-migrations#173]
when i run a project I get the error
```
2023/07/20 19:46:29 initializing database ...
2023/07/20 19:46:29 Your programs version (13) is lower than your repos (14).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.
panic: Your programs version (13) is lower than your repos (14).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.


goroutine 1 [running]:
log.Panicln({0xc00053ff48?, 0xc0006a8240?, 0xc000048840?})
        /usr/local/opt/go/libexec/src/log/log.go:402 +0x65
main.main()
        /Users/panzhuochen/repository/superhighway84/superhighway84.go:89 +0x63d

```

and i visit the website:https://github.com/ipfs/fs-repo-migrations/blob/master/run.md
download the fs-repo-migrations and run ./fs-repo-migrations
but get the error:
```
Could not get available repo migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipns/dist.ipfs.io/fs-repo-10-to-11/versions": dial tcp 54.89.135.129:443: connect: connection refused
```

I cannot solve it,please give me some advice,tks~

**Comment by timecool-cpu** [comment]
I think that is the result of error in http.DefaultClient?I cannot get the solution.

**Comment by hsanjuan** [comment]
Update Kubo. The ipfs.io issue might just be transient.
